apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: grade-submission-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grade-submission
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateless-v2 #  v4 is standard v2 has been designed to intaract with a stateless DB # v3 hass bee designed for db assword access
          livenessProbe:
            httpGet:
              path: /healthz  
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5     
          readinessProbe:
            httpGet:
              path: /readyz  
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: '27017'
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 3000
        - name: grade-submission-api-health-checker
          image: rslim087/kubernetes-course-grade-submission-api-health-checker
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
