kind: Service
apiVersion: v1
metadata:
  name:  mongodb
  namespace: grade-submission
spec:
  selector:
    app.kubernetes.io/instance: mongodb
  type:  ClusterIP 
  ports:
  - port:  27017
    targetPort:  27017