kind: Service
apiVersion: v1
metadata:
  name:  grade-submission-api
  namespace: grade-submission
spec:
  selector:
     app.kubernetes.io/instance: grade-submission-api
  type: ClusterIP
  ports:
  - port:  3000
    targetPort:  3000
