apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: grade-submission
  labels:
    app.kubernetes.io/name: grade-submission
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: grade-submission-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grade-submission
      app.kubernetes.io/component: backend
      app.kubernetes.io/instance: grade-submission-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grade-submission
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: grade-submission-api
    spec:
      containers:
        - name: grade-submission-api
          image: rslim087/kubernetes-course-grade-submission-api:stateless-v4
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 3000
        - name: grade-submission-api-health-checker
          image: rslim087/kubernetes-course-grade-submission-api-health-checker
          resources:
            requests:
              cpu: "128m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
